#define JGKP_var_template_small_grp ["JGKP_T8_smallGrp1", "JGKP_T8_smallGrp2", "JGKP_T8_smallGrp3", "JGKP_T8_smallGrp4"]
#define JGKP_var_template_big_grp 	["JGKP_T8_bigGrp1", "JGKP_T8_bigGrp2", "JGKP_T8_bigGrp3"]
#define JGKP_var_template_motorized ["JGKP_T8_motGrp1", "JGKP_T8_motGrp2", "JGKP_T8_motGrp3"]
#define JGKP_var_template_car 		["JGKP_T8_car1", "JGKP_T8_car2", "JGKP_T8_car3"]
#define JGKP_var_template_static 	["JGKP_T8_stat1", "JGKP_T8_stat2", "JGKP_T8_stat3", "JGKP_T8_stat4", "JGKP_T8_stat5"]
#define JGKP_var_template_armored 	["JGKP_T8_tank1", "JGKP_T8_tank2", "JGKP_T8_tank3", "JGKP_T8_tank4"]
